package com.stern.mapper;

import com.stern.pojo.TblOrder;
import com.stern.pojo.TblOrderExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface TblOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated
     */
    long countByExample(TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated
     */
    int deleteByExample(TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated
     */
    int insert(TblOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated
     */
    int insertSelective(TblOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated
     */
    List<TblOrder> selectByExample(TblOrderExample example);
    List<TblOrder> selectAllOrderWithMember(String mname);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated
     */
    TblOrder selectByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TblOrder record, @Param("example") TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TblOrder record, @Param("example") TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TblOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TblOrder record);
}