package com.stern.pojo;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classid
     *
     * @mbg.generated
     */
    private Integer classid;
    private Integer haveOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classtime
     *
     * @mbg.generated
     */
    private String classtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.empl_id
     *
     * @mbg.generated
     */
    private Integer emplId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classvolume
     *
     * @mbg.generated
     */
    private Integer classvolume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classid
     *
     * @return the value of class.classid
     *
     * @mbg.generated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classid
     *
     * @param classid the value for class.classid
     *
     * @mbg.generated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    public Integer getHaveOrder() {
        return haveOrder;
    }

    public void setHaveOrder(Integer haveOrder) {
        this.haveOrder = haveOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.course_id
     *
     * @return the value of class.course_id
     *
     * @mbg.generated
     */

    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.course_id
     *
     * @param courseId the value for class.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classtime
     *
     * @return the value of class.classtime
     *
     * @mbg.generated
     */
    public String getClasstime() {
        return classtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classtime
     *
     * @param classtime the value for class.classtime
     *
     * @mbg.generated
     */
    public void setClasstime(String classtime) {
        this.classtime = classtime == null ? null : classtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.empl_id
     *
     * @return the value of class.empl_id
     *
     * @mbg.generated
     */
    public Integer getEmplId() {
        return emplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.empl_id
     *
     * @param emplId the value for class.empl_id
     *
     * @mbg.generated
     */
    public void setEmplId(Integer emplId) {
        this.emplId = emplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classvolume
     *
     * @return the value of class.classvolume
     *
     * @mbg.generated
     */
    public Integer getClassvolume() {
        return classvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classvolume
     *
     * @param classvolume the value for class.classvolume
     *
     * @mbg.generated
     */
    public void setClassvolume(Integer classvolume) {
        this.classvolume = classvolume;
    }
}