package com.stern.pojo;

/**
 * 课程功能 -实体类
 */
public class Coursefunction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursefunction.fid
     *
     * @mbg.generated
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursefunction.fname
     *
     * @mbg.generated
     */
    private String fname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursefunction.fid
     *
     * @return the value of coursefunction.fid
     *
     * @mbg.generated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursefunction.fid
     *
     * @param fid the value for coursefunction.fid
     *
     * @mbg.generated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursefunction.fname
     *
     * @return the value of coursefunction.fname
     *
     * @mbg.generated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursefunction.fname
     *
     * @param fname the value for coursefunction.fname
     *
     * @mbg.generated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }
}