package com.stern.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EmployeeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    public EmployeeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEidIsNull() {
            addCriterion("eid is null");
            return (Criteria) this;
        }

        public Criteria andEidIsNotNull() {
            addCriterion("eid is not null");
            return (Criteria) this;
        }

        public Criteria andEidEqualTo(Integer value) {
            addCriterion("eid =", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotEqualTo(Integer value) {
            addCriterion("eid <>", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThan(Integer value) {
            addCriterion("eid >", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThanOrEqualTo(Integer value) {
            addCriterion("eid >=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThan(Integer value) {
            addCriterion("eid <", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThanOrEqualTo(Integer value) {
            addCriterion("eid <=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidIn(List<Integer> values) {
            addCriterion("eid in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotIn(List<Integer> values) {
            addCriterion("eid not in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidBetween(Integer value1, Integer value2) {
            addCriterion("eid between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotBetween(Integer value1, Integer value2) {
            addCriterion("eid not between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andEnameIsNull() {
            addCriterion("ename is null");
            return (Criteria) this;
        }

        public Criteria andEnameIsNotNull() {
            addCriterion("ename is not null");
            return (Criteria) this;
        }

        public Criteria andEnameEqualTo(String value) {
            addCriterion("ename =", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotEqualTo(String value) {
            addCriterion("ename <>", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThan(String value) {
            addCriterion("ename >", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThanOrEqualTo(String value) {
            addCriterion("ename >=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThan(String value) {
            addCriterion("ename <", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThanOrEqualTo(String value) {
            addCriterion("ename <=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLike(String value) {
            addCriterion("ename like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotLike(String value) {
            addCriterion("ename not like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameIn(List<String> values) {
            addCriterion("ename in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotIn(List<String> values) {
            addCriterion("ename not in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameBetween(String value1, String value2) {
            addCriterion("ename between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotBetween(String value1, String value2) {
            addCriterion("ename not between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andEgenderIsNull() {
            addCriterion("egender is null");
            return (Criteria) this;
        }

        public Criteria andEgenderIsNotNull() {
            addCriterion("egender is not null");
            return (Criteria) this;
        }

        public Criteria andEgenderEqualTo(Byte value) {
            addCriterion("egender =", value, "egender");
            return (Criteria) this;
        }

        public Criteria andEgenderNotEqualTo(Byte value) {
            addCriterion("egender <>", value, "egender");
            return (Criteria) this;
        }

        public Criteria andEgenderGreaterThan(Byte value) {
            addCriterion("egender >", value, "egender");
            return (Criteria) this;
        }

        public Criteria andEgenderGreaterThanOrEqualTo(Byte value) {
            addCriterion("egender >=", value, "egender");
            return (Criteria) this;
        }

        public Criteria andEgenderLessThan(Byte value) {
            addCriterion("egender <", value, "egender");
            return (Criteria) this;
        }

        public Criteria andEgenderLessThanOrEqualTo(Byte value) {
            addCriterion("egender <=", value, "egender");
            return (Criteria) this;
        }

        public Criteria andEgenderIn(List<Byte> values) {
            addCriterion("egender in", values, "egender");
            return (Criteria) this;
        }

        public Criteria andEgenderNotIn(List<Byte> values) {
            addCriterion("egender not in", values, "egender");
            return (Criteria) this;
        }

        public Criteria andEgenderBetween(Byte value1, Byte value2) {
            addCriterion("egender between", value1, value2, "egender");
            return (Criteria) this;
        }

        public Criteria andEgenderNotBetween(Byte value1, Byte value2) {
            addCriterion("egender not between", value1, value2, "egender");
            return (Criteria) this;
        }

        public Criteria andEphoneIsNull() {
            addCriterion("ephone is null");
            return (Criteria) this;
        }

        public Criteria andEphoneIsNotNull() {
            addCriterion("ephone is not null");
            return (Criteria) this;
        }

        public Criteria andEphoneEqualTo(String value) {
            addCriterion("ephone =", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneNotEqualTo(String value) {
            addCriterion("ephone <>", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneGreaterThan(String value) {
            addCriterion("ephone >", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneGreaterThanOrEqualTo(String value) {
            addCriterion("ephone >=", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneLessThan(String value) {
            addCriterion("ephone <", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneLessThanOrEqualTo(String value) {
            addCriterion("ephone <=", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneLike(String value) {
            addCriterion("ephone like", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneNotLike(String value) {
            addCriterion("ephone not like", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneIn(List<String> values) {
            addCriterion("ephone in", values, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneNotIn(List<String> values) {
            addCriterion("ephone not in", values, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneBetween(String value1, String value2) {
            addCriterion("ephone between", value1, value2, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneNotBetween(String value1, String value2) {
            addCriterion("ephone not between", value1, value2, "ephone");
            return (Criteria) this;
        }

        public Criteria andEpostIdIsNull() {
            addCriterion("epost_id is null");
            return (Criteria) this;
        }

        public Criteria andEpostIdIsNotNull() {
            addCriterion("epost_id is not null");
            return (Criteria) this;
        }

        public Criteria andEpostIdEqualTo(Integer value) {
            addCriterion("epost_id =", value, "epostId");
            return (Criteria) this;
        }

        public Criteria andEpostIdNotEqualTo(Integer value) {
            addCriterion("epost_id <>", value, "epostId");
            return (Criteria) this;
        }

        public Criteria andEpostIdGreaterThan(Integer value) {
            addCriterion("epost_id >", value, "epostId");
            return (Criteria) this;
        }

        public Criteria andEpostIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("epost_id >=", value, "epostId");
            return (Criteria) this;
        }

        public Criteria andEpostIdLessThan(Integer value) {
            addCriterion("epost_id <", value, "epostId");
            return (Criteria) this;
        }

        public Criteria andEpostIdLessThanOrEqualTo(Integer value) {
            addCriterion("epost_id <=", value, "epostId");
            return (Criteria) this;
        }

        public Criteria andEpostIdIn(List<Integer> values) {
            addCriterion("epost_id in", values, "epostId");
            return (Criteria) this;
        }

        public Criteria andEpostIdNotIn(List<Integer> values) {
            addCriterion("epost_id not in", values, "epostId");
            return (Criteria) this;
        }

        public Criteria andEpostIdBetween(Integer value1, Integer value2) {
            addCriterion("epost_id between", value1, value2, "epostId");
            return (Criteria) this;
        }

        public Criteria andEpostIdNotBetween(Integer value1, Integer value2) {
            addCriterion("epost_id not between", value1, value2, "epostId");
            return (Criteria) this;
        }

        public Criteria andEaddIsNull() {
            addCriterion("eadd is null");
            return (Criteria) this;
        }

        public Criteria andEaddIsNotNull() {
            addCriterion("eadd is not null");
            return (Criteria) this;
        }

        public Criteria andEaddEqualTo(String value) {
            addCriterion("eadd =", value, "eadd");
            return (Criteria) this;
        }

        public Criteria andEaddNotEqualTo(String value) {
            addCriterion("eadd <>", value, "eadd");
            return (Criteria) this;
        }

        public Criteria andEaddGreaterThan(String value) {
            addCriterion("eadd >", value, "eadd");
            return (Criteria) this;
        }

        public Criteria andEaddGreaterThanOrEqualTo(String value) {
            addCriterion("eadd >=", value, "eadd");
            return (Criteria) this;
        }

        public Criteria andEaddLessThan(String value) {
            addCriterion("eadd <", value, "eadd");
            return (Criteria) this;
        }

        public Criteria andEaddLessThanOrEqualTo(String value) {
            addCriterion("eadd <=", value, "eadd");
            return (Criteria) this;
        }

        public Criteria andEaddLike(String value) {
            addCriterion("eadd like", value, "eadd");
            return (Criteria) this;
        }

        public Criteria andEaddNotLike(String value) {
            addCriterion("eadd not like", value, "eadd");
            return (Criteria) this;
        }

        public Criteria andEaddIn(List<String> values) {
            addCriterion("eadd in", values, "eadd");
            return (Criteria) this;
        }

        public Criteria andEaddNotIn(List<String> values) {
            addCriterion("eadd not in", values, "eadd");
            return (Criteria) this;
        }

        public Criteria andEaddBetween(String value1, String value2) {
            addCriterion("eadd between", value1, value2, "eadd");
            return (Criteria) this;
        }

        public Criteria andEaddNotBetween(String value1, String value2) {
            addCriterion("eadd not between", value1, value2, "eadd");
            return (Criteria) this;
        }

        public Criteria andEhireIsNull() {
            addCriterion("ehire is null");
            return (Criteria) this;
        }

        public Criteria andEhireIsNotNull() {
            addCriterion("ehire is not null");
            return (Criteria) this;
        }

        public Criteria andEhireEqualTo(Date value) {
            addCriterion("ehire =", value, "ehire");
            return (Criteria) this;
        }

        public Criteria andEhireNotEqualTo(Date value) {
            addCriterion("ehire <>", value, "ehire");
            return (Criteria) this;
        }

        public Criteria andEhireGreaterThan(Date value) {
            addCriterion("ehire >", value, "ehire");
            return (Criteria) this;
        }

        public Criteria andEhireGreaterThanOrEqualTo(Date value) {
            addCriterion("ehire >=", value, "ehire");
            return (Criteria) this;
        }

        public Criteria andEhireLessThan(Date value) {
            addCriterion("ehire <", value, "ehire");
            return (Criteria) this;
        }

        public Criteria andEhireLessThanOrEqualTo(Date value) {
            addCriterion("ehire <=", value, "ehire");
            return (Criteria) this;
        }

        public Criteria andEhireIn(List<Date> values) {
            addCriterion("ehire in", values, "ehire");
            return (Criteria) this;
        }

        public Criteria andEhireNotIn(List<Date> values) {
            addCriterion("ehire not in", values, "ehire");
            return (Criteria) this;
        }

        public Criteria andEhireBetween(Date value1, Date value2) {
            addCriterion("ehire between", value1, value2, "ehire");
            return (Criteria) this;
        }

        public Criteria andEhireNotBetween(Date value1, Date value2) {
            addCriterion("ehire not between", value1, value2, "ehire");
            return (Criteria) this;
        }

        public Criteria andEstateIsNull() {
            addCriterion("estate is null");
            return (Criteria) this;
        }

        public Criteria andEstateIsNotNull() {
            addCriterion("estate is not null");
            return (Criteria) this;
        }

        public Criteria andEstateEqualTo(Integer value) {
            addCriterion("estate =", value, "estate");
            return (Criteria) this;
        }

        public Criteria andEstateNotEqualTo(Integer value) {
            addCriterion("estate <>", value, "estate");
            return (Criteria) this;
        }

        public Criteria andEstateGreaterThan(Integer value) {
            addCriterion("estate >", value, "estate");
            return (Criteria) this;
        }

        public Criteria andEstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("estate >=", value, "estate");
            return (Criteria) this;
        }

        public Criteria andEstateLessThan(Integer value) {
            addCriterion("estate <", value, "estate");
            return (Criteria) this;
        }

        public Criteria andEstateLessThanOrEqualTo(Integer value) {
            addCriterion("estate <=", value, "estate");
            return (Criteria) this;
        }

        public Criteria andEstateIn(List<Integer> values) {
            addCriterion("estate in", values, "estate");
            return (Criteria) this;
        }

        public Criteria andEstateNotIn(List<Integer> values) {
            addCriterion("estate not in", values, "estate");
            return (Criteria) this;
        }

        public Criteria andEstateBetween(Integer value1, Integer value2) {
            addCriterion("estate between", value1, value2, "estate");
            return (Criteria) this;
        }

        public Criteria andEstateNotBetween(Integer value1, Integer value2) {
            addCriterion("estate not between", value1, value2, "estate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}