package com.stern.pojo;

import java.util.Date;

/**
 * 员工 -实体类
 */
public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.eid
     *
     * @mbg.generated
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.ename
     *
     * @mbg.generated
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.egender
     *
     * @mbg.generated
     */
    private Byte egender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.ephone
     *
     * @mbg.generated
     */
    private String ephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.epost_id
     *
     * @mbg.generated
     */
    private Integer epostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.eadd
     *
     * @mbg.generated
     */
    private String eadd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.ehire
     *
     * @mbg.generated
     */
    private Date ehire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.estate
     *
     * @mbg.generated
     */
    private Integer estate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.eid
     *
     * @return the value of employee.eid
     *
     * @mbg.generated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.eid
     *
     * @param eid the value for employee.eid
     *
     * @mbg.generated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.ename
     *
     * @return the value of employee.ename
     *
     * @mbg.generated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.ename
     *
     * @param ename the value for employee.ename
     *
     * @mbg.generated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.egender
     *
     * @return the value of employee.egender
     *
     * @mbg.generated
     */
    public Byte getEgender() {
        return egender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.egender
     *
     * @param egender the value for employee.egender
     *
     * @mbg.generated
     */
    public void setEgender(Byte egender) {
        this.egender = egender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.ephone
     *
     * @return the value of employee.ephone
     *
     * @mbg.generated
     */
    public String getEphone() {
        return ephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.ephone
     *
     * @param ephone the value for employee.ephone
     *
     * @mbg.generated
     */
    public void setEphone(String ephone) {
        this.ephone = ephone == null ? null : ephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.epost_id
     *
     * @return the value of employee.epost_id
     *
     * @mbg.generated
     */
    public Integer getEpostId() {
        return epostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.epost_id
     *
     * @param epostId the value for employee.epost_id
     *
     * @mbg.generated
     */
    public void setEpostId(Integer epostId) {
        this.epostId = epostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.eadd
     *
     * @return the value of employee.eadd
     *
     * @mbg.generated
     */
    public String getEadd() {
        return eadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.eadd
     *
     * @param eadd the value for employee.eadd
     *
     * @mbg.generated
     */
    public void setEadd(String eadd) {
        this.eadd = eadd == null ? null : eadd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.ehire
     *
     * @return the value of employee.ehire
     *
     * @mbg.generated
     */
    public Date getEhire() {
        return ehire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.ehire
     *
     * @param ehire the value for employee.ehire
     *
     * @mbg.generated
     */
    public void setEhire(Date ehire) {
        this.ehire = ehire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.estate
     *
     * @return the value of employee.estate
     *
     * @mbg.generated
     */
    public Integer getEstate() {
        return estate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.estate
     *
     * @param estate the value for employee.estate
     *
     * @mbg.generated
     */
    public void setEstate(Integer estate) {
        this.estate = estate;
    }
}