package com.stern.pojo;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import java.util.Date;

/**
 * 会员 -实体类
 */
public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mname
     *
     * @mbg.generated
     */
    @NotNull(message = "姓名不能为空")
    @Size(min = 3,max = 6,message = "姓名长度应在{min}-{max}之间")
    private String mname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mpassword
     *
     * @mbg.generated
     */
    @Size(min = 6,message = "密码长度至少{min}位")
    private String mpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mgender
     *
     * @mbg.generated
     */
    private Integer mgender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.midno
     *
     * @mbg.generated
     */
    @NotNull(message = "身份证号不能为空")
    @Size(max = 18,min = 18,message = "请确保身份证号码为{max}位")
    private String midno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mphone
     *
     * @mbg.generated
     */
    @NotNull(message = "手机号码不能为空")
    @Pattern(regexp = "^((13[0-9])|(15[^4,\\\\D])|(17[0-9])|(18[0-9]))\\d{8}$",message = "请输入正确的手机号码")
    private String mphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memail
     *
     * @mbg.generated
     */
    @NotNull(message = "邮箱不能为空")
    @Email(message = "请确保为正确邮箱")
    private String memail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mdate
     *
     * @mbg.generated
     */
    private Date mdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mid
     *
     * @return the value of member.mid
     *
     * @mbg.generated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mid
     *
     * @param mid the value for member.mid
     *
     * @mbg.generated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mname
     *
     * @return the value of member.mname
     *
     * @mbg.generated
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mname
     *
     * @param mname the value for member.mname
     *
     * @mbg.generated
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mpassword
     *
     * @return the value of member.mpassword
     *
     * @mbg.generated
     */
    public String getMpassword() {
        return mpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mpassword
     *
     * @param mpassword the value for member.mpassword
     *
     * @mbg.generated
     */
    public void setMpassword(String mpassword) {
        this.mpassword = mpassword == null ? null : mpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mgender
     *
     * @return the value of member.mgender
     *
     * @mbg.generated
     */
    public Integer getMgender() {
        return mgender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mgender
     *
     * @param mgender the value for member.mgender
     *
     * @mbg.generated
     */

    public void setMgender(Integer mgender) {
        this.mgender = mgender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.midno
     *
     * @return the value of member.midno
     *
     * @mbg.generated
     */
    public String getMidno() {
        return midno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.midno
     *
     * @param midno the value for member.midno
     *
     * @mbg.generated
     */
    public void setMidno(String midno) {
        this.midno = midno == null ? null : midno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mphone
     *
     * @return the value of member.mphone
     *
     * @mbg.generated
     */
    public String getMphone() {
        return mphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mphone
     *
     * @param mphone the value for member.mphone
     *
     * @mbg.generated
     */
    public void setMphone(String mphone) {
        this.mphone = mphone == null ? null : mphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memail
     *
     * @return the value of member.memail
     *
     * @mbg.generated
     */
    public String getMemail() {
        return memail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memail
     *
     * @param memail the value for member.memail
     *
     * @mbg.generated
     */
    public void setMemail(String memail) {
        this.memail = memail == null ? null : memail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mdate
     *
     * @return the value of member.mdate
     *
     * @mbg.generated
     */
    public Date getMdate() {
        return mdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mdate
     *
     * @param mdate the value for member.mdate
     *
     * @mbg.generated
     */
    public void setMdate(Date mdate) {
        this.mdate = mdate;
    }
}