package com.stern.pojo;

import java.util.ArrayList;
import java.util.List;

public class NewskindsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    public NewskindsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNkidIsNull() {
            addCriterion("nkid is null");
            return (Criteria) this;
        }

        public Criteria andNkidIsNotNull() {
            addCriterion("nkid is not null");
            return (Criteria) this;
        }

        public Criteria andNkidEqualTo(Integer value) {
            addCriterion("nkid =", value, "nkid");
            return (Criteria) this;
        }

        public Criteria andNkidNotEqualTo(Integer value) {
            addCriterion("nkid <>", value, "nkid");
            return (Criteria) this;
        }

        public Criteria andNkidGreaterThan(Integer value) {
            addCriterion("nkid >", value, "nkid");
            return (Criteria) this;
        }

        public Criteria andNkidGreaterThanOrEqualTo(Integer value) {
            addCriterion("nkid >=", value, "nkid");
            return (Criteria) this;
        }

        public Criteria andNkidLessThan(Integer value) {
            addCriterion("nkid <", value, "nkid");
            return (Criteria) this;
        }

        public Criteria andNkidLessThanOrEqualTo(Integer value) {
            addCriterion("nkid <=", value, "nkid");
            return (Criteria) this;
        }

        public Criteria andNkidIn(List<Integer> values) {
            addCriterion("nkid in", values, "nkid");
            return (Criteria) this;
        }

        public Criteria andNkidNotIn(List<Integer> values) {
            addCriterion("nkid not in", values, "nkid");
            return (Criteria) this;
        }

        public Criteria andNkidBetween(Integer value1, Integer value2) {
            addCriterion("nkid between", value1, value2, "nkid");
            return (Criteria) this;
        }

        public Criteria andNkidNotBetween(Integer value1, Integer value2) {
            addCriterion("nkid not between", value1, value2, "nkid");
            return (Criteria) this;
        }

        public Criteria andNknameIsNull() {
            addCriterion("nkname is null");
            return (Criteria) this;
        }

        public Criteria andNknameIsNotNull() {
            addCriterion("nkname is not null");
            return (Criteria) this;
        }

        public Criteria andNknameEqualTo(String value) {
            addCriterion("nkname =", value, "nkname");
            return (Criteria) this;
        }

        public Criteria andNknameNotEqualTo(String value) {
            addCriterion("nkname <>", value, "nkname");
            return (Criteria) this;
        }

        public Criteria andNknameGreaterThan(String value) {
            addCriterion("nkname >", value, "nkname");
            return (Criteria) this;
        }

        public Criteria andNknameGreaterThanOrEqualTo(String value) {
            addCriterion("nkname >=", value, "nkname");
            return (Criteria) this;
        }

        public Criteria andNknameLessThan(String value) {
            addCriterion("nkname <", value, "nkname");
            return (Criteria) this;
        }

        public Criteria andNknameLessThanOrEqualTo(String value) {
            addCriterion("nkname <=", value, "nkname");
            return (Criteria) this;
        }

        public Criteria andNknameLike(String value) {
            addCriterion("nkname like", value, "nkname");
            return (Criteria) this;
        }

        public Criteria andNknameNotLike(String value) {
            addCriterion("nkname not like", value, "nkname");
            return (Criteria) this;
        }

        public Criteria andNknameIn(List<String> values) {
            addCriterion("nkname in", values, "nkname");
            return (Criteria) this;
        }

        public Criteria andNknameNotIn(List<String> values) {
            addCriterion("nkname not in", values, "nkname");
            return (Criteria) this;
        }

        public Criteria andNknameBetween(String value1, String value2) {
            addCriterion("nkname between", value1, value2, "nkname");
            return (Criteria) this;
        }

        public Criteria andNknameNotBetween(String value1, String value2) {
            addCriterion("nkname not between", value1, value2, "nkname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newskinds
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newskinds
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}