package com.stern.pojo;

public class Newskinds {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newskinds.nkid
     *
     * @mbg.generated
     */
    private Integer nkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newskinds.nkname
     *
     * @mbg.generated
     */
    private String nkname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newskinds.nkid
     *
     * @return the value of newskinds.nkid
     *
     * @mbg.generated
     */
    public Integer getNkid() {
        return nkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newskinds.nkid
     *
     * @param nkid the value for newskinds.nkid
     *
     * @mbg.generated
     */
    public void setNkid(Integer nkid) {
        this.nkid = nkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newskinds.nkname
     *
     * @return the value of newskinds.nkname
     *
     * @mbg.generated
     */
    public String getNkname() {
        return nkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newskinds.nkname
     *
     * @param nkname the value for newskinds.nkname
     *
     * @mbg.generated
     */
    public void setNkname(String nkname) {
        this.nkname = nkname == null ? null : nkname.trim();
    }
}