package com.stern.pojo;

import java.util.Date;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.rid
     *
     * @mbg.generated
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.rcontent
     *
     * @mbg.generated
     */
    private String rcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.rdate
     *
     * @mbg.generated
     */
    private Date rdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.r_msg_id
     *
     * @mbg.generated
     */
    private Integer rMsgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.rid
     *
     * @return the value of reply.rid
     *
     * @mbg.generated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.rid
     *
     * @param rid the value for reply.rid
     *
     * @mbg.generated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.rcontent
     *
     * @return the value of reply.rcontent
     *
     * @mbg.generated
     */
    public String getRcontent() {
        return rcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.rcontent
     *
     * @param rcontent the value for reply.rcontent
     *
     * @mbg.generated
     */
    public void setRcontent(String rcontent) {
        this.rcontent = rcontent == null ? null : rcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.rdate
     *
     * @return the value of reply.rdate
     *
     * @mbg.generated
     */
    public Date getRdate() {
        return rdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.rdate
     *
     * @param rdate the value for reply.rdate
     *
     * @mbg.generated
     */
    public void setRdate(Date rdate) {
        this.rdate = rdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.r_msg_id
     *
     * @return the value of reply.r_msg_id
     *
     * @mbg.generated
     */
    public Integer getrMsgId() {
        return rMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.r_msg_id
     *
     * @param rMsgId the value for reply.r_msg_id
     *
     * @mbg.generated
     */
    public void setrMsgId(Integer rMsgId) {
        this.rMsgId = rMsgId;
    }
}