package com.stern.pojo;

public class Sheet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheet.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheet.ssrc
     *
     * @mbg.generated
     */
    private String ssrc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheet.sid
     *
     * @return the value of sheet.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheet.sid
     *
     * @param sid the value for sheet.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheet.ssrc
     *
     * @return the value of sheet.ssrc
     *
     * @mbg.generated
     */
    public String getSsrc() {
        return ssrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheet.ssrc
     *
     * @param ssrc the value for sheet.ssrc
     *
     * @mbg.generated
     */
    public void setSsrc(String ssrc) {
        this.ssrc = ssrc == null ? null : ssrc.trim();
    }
}